# Generated by Django 5.0.2 on 2024-02-15 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_txt", models.CharField(max_length=100)),
                ("desc_txt", models.CharField(max_length=200)),
                ("raw_disclaimer", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_txt", models.CharField(max_length=100)),
                ("desc_txt", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("raw_disclaimer", models.BooleanField()),
                ("image", models.ImageField(blank=True, upload_to="menu_images/")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.menusection",
                    ),
                ),
            ],
        ),
    ]
