# Generated by Django 5.0.2 on 2024-02-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_menuitem_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="title_txt",
            new_name="display_txt",
        ),
    ]
