"""
Django settings for savoy project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from os import environ
from pathlib import Path


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environ.get("DJANGO_DEBUG")

if DEBUG is True or DEBUG == "True":
    print("running in debug mode")
    BASE_DIR = Path(__file__).resolve().parent.parent
    ALLOWED_HOSTS = []

    STATIC_ROOT = os.path.join(BASE_DIR, 'dbg/static')
    MEDIA_ROOT = os.path.join(BASE_DIR, 'dbg/media')
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'

    DB_PATH = os.path.join(BASE_DIR, 'db.sqlite3')

else:
    print("running in production mode")
    BASE_DIR = Path(__file__).resolve().parent
    ALLOWED_HOSTS = [environ.get("DJANGO_STATIC_HOST")]

    STATIC_ROOT = environ.get("DJANGO_STATIC_ROOT")
    MEDIA_ROOT = environ.get("DJANGO_MEDIA_ROOT")
    STATIC_URL = environ.get("DJANGO_STATIC_URL")
    MEDIA_URL = environ.get("DJANGO_MEDIA_URL")

    DB_PATH = environ.get("DJANGO_DB_PATH")

print(f"DEBUG: {DEBUG}")
print(f"BASE_DIR: {BASE_DIR}")
print(f"STATIC_ROOT: {STATIC_ROOT}")
print(f"MEDIA_ROOT: {MEDIA_ROOT}")
print(f"STATIC_URL: {STATIC_URL}")
print(f"MEDIA_URL: {MEDIA_URL}")
print(f"DB_PATH: {DB_PATH}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-r5qu-$s*4-q886-in9_sg)8=-5s8!pgw0ws%x@w)jnc6apbm%1"

ALLOWED_HOSTS = ['localhost']

# Both static and media files need to be served by a web proxy like Nginx
# in production. The dev server will serve them directly for testing.

# Static file route - Added to find global static files in ../static/css/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Application definition

INSTALLED_APPS = [
    "home.apps.HomeConfig",
    "location.apps.LocationConfig",
    "menu.apps.MenuConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "savoy.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "savoy.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
