# Generated by Django 5.0.2 on 2024-02-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationsStops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_txt", models.CharField(max_length=200)),
                ("hours_txt", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LocationsWeekdays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday_txt", models.CharField(max_length=100)),
                ("stops", models.ManyToManyField(to="locations.locationsstops")),
            ],
        ),
    ]
