set shell := ["/opt/homebrew/bin/fish", "-c"]

# starts local development server
start:
	python manage.py runserver

# run to migrate database when models have changed
migrate:
	python manage.py migrate

# run to generate a new migration when another app is added
make_migration APP:
	python manage.py makemigration {{ APP }}
