---
- name: Add systemd unit file
  ansible.builtin.template:
    src: 'container-{{ chaos_name }}.service'
    dest: '/home/{{ g_user }}/.config/systemd/user/'
    owner: '{{ g_user }}'
    mode: '0644'
  notify:
    - Restart service

- name: Clone repo
  ansible.builtin.git:
    repo: "git@github.com:acbilson/chaos-{{ chaos_name }}.git"
    dest: "{{ g_src_path }}/chaos-{{ chaos_name }}"
    depth: 1
    single_branch: true
    version: main
    key_file: '{{ g_mnt_path }}/git/git_rsa'
  become_user: '{{ g_user }}'

- name: Build the Podman image
  containers.podman.podman_image:
    name: 'localhost/acbilson/{{ chaos_name }}:latest'
    path: '{{ g_src_path }}/chaos-{{ chaos_name }}'
    build:
      format: docker
  become_user: '{{ g_user }}'

- name: Enable service
  ansible.builtin.systemd:
    name: 'container-{{ chaos_name }}'
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  become_user: '{{ g_user }}'

- name: Create a log directory
  ansible.builtin.file:
    path: '/var/log/nginx/{{ chaos_name }}'
    state: directory
    mode: '0755'

- name: Add Nginx config
  ansible.builtin.template:
    src: '{{ chaos_name }}.conf'
    dest: '/etc/nginx/sites-available/{{ repo_name }}.conf'
    mode: '0644'

- name: Enable proxy
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/{{ repo_name }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ repo_name }}.conf'
    state: link
  notify:
    - Restart nginx

- name: Configure for CI/CD
  ansible.builtin.include_role:
    name: ci_repo
